export enum StockMovementType {
  OPENING = 'OPENING',

  PURCHASE = 'PURCHASE',

  PURCHASE_RETURN = 'PURCHASE_RETURN',

  SALES = 'SALES',

  SALES_RETURN = 'SALES_RETURN',

  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',

  STOCK_TRANSFER_IN = 'STOCK_TRANSFER_IN',

  STOCK_TRANSFER_OUT = 'STOCK_TRANSFER_OUT',

  PRODUCTION_IN = 'PRODUCTION_IN',

  PRODUCTION_OUT = 'PRODUCTION_OUT',
}